# Generated by Django 5.0.13 on 2026-02-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title or date', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one session should be active at a time')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='commands_te_is_acti_041435_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField(help_text='The command text (no output)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='commands.teachingsession')),
            ],
            options={
                'verbose_name_plural': 'Command entries',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='commands_co_session_7b7b7e_idx')],
            },
        ),
    ]
